In [1]:
from utilities.std_imports import *
import time
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.utils.data
import torch.optim as optim
from torch.autograd import Variable

In [2]:
print(torch.cuda.current_device())
print(torch.cuda.is_available())

0
True


In [3]:
start = time.time()
t1 = torch.FloatTensor(10,10)
t2 = torch.FloatTensor(10,10)
t3 = t1.matmul(t2)
end = time.time()
print('CPU ', end-start)
print(t3)

start = time.time()
t1 = torch.cuda.FloatTensor(10,10)
t2 = torch.cuda.FloatTensor(10,10)
t3 = t1.matmul(t2)
end = time.time()
print('GPU ', end-start)
print(t3)

CPU  0.001993894577026367
tensor([[       inf,        inf,        inf,        inf,        nan,        nan,
                inf, 5.8098e+27,        inf, 3.1967e+27],
        [       inf,        inf,        inf,        inf,        nan,        nan,
                inf, 6.6230e+25,        inf,        inf],
        [       inf,        inf,        inf,        inf,        nan,        nan,
                inf,        inf,        inf,        inf],
        [       inf,        inf,        inf,        inf,        nan,        nan,
                inf,        inf,        inf,        inf],
        [       inf,        inf,        inf,        inf,        nan,        nan,
                inf,        inf,        inf,        inf],
        [       inf,        inf,        inf,        inf,        nan,        nan,
                inf,        inf,        inf,        inf],
        [       inf,        inf,        inf,        inf,        nan,        nan,
                inf, 2.2555e+33,        inf,        inf],
 

## From scratch

In [4]:
#Input array
X = torch.Tensor([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y = torch.Tensor([[1],[1],[0]])

#Sigmoid Function
def sigmoid (x):
  return 1/(1 + torch.exp(-x))

#Derivative of Sigmoid Function
def deriv_sigmoid(x):
  return x * (1 - x)

#Hypers
epochs=5000 
lr=0.1 
inp = X.shape[1] 
hid = 3
out = 1

# weight and bias initialization
W_hid = torch.randn(inp, hid).type(torch.FloatTensor)
b_hid = torch.randn(1, hid).type(torch.FloatTensor)
W_out = torch.randn(hid, out)
b_out = torch.randn(1, out)

In [5]:
for i in range(epochs):

  #Forward step
  hid_inp1 = torch.mm(X, W_hid)
  hid_inp = hid_inp1 + b_hid
  hid_act = sigmoid(hid_inp)
 
  out_inp1 = torch.mm(hid_act, W_out)
  out_inp = out_inp1 + b_out
  out = sigmoid(out_inp1)

  #Backward step
  E = y-out
  slope_out = deriv_sigmoid(out)
  slope_hid = deriv_sigmoid(hid_act)
  d_out = E * slope_out
  err_hid = torch.mm(d_out, W_out.t())
  d_hid = err_hid * slope_hid
  W_out += torch.mm(hid_act.t(), d_out) * lr
  b_out += d_out.sum() * lr
  W_hid += torch.mm(X.t(), d_hid) * lr
  b_hid += d_out.sum() * lr
 
'actual:', y, 'predicted:', out

('actual:',
 tensor([[1.],
         [1.],
         [0.]]),
 'predicted:',
 tensor([[0.9840],
         [0.9756],
         [0.0371]]))

In [38]:
ff = FF(inp=4, hid=3)
ff.forward(X)

tensor([[0.4851],
        [0.4196],
        [0.4564]], grad_fn=<AddmmBackward>)

In [41]:
for _ in range(epochs):
      out = ff.forward(X)  
 
'actual:', y, 'predicted:', out

('actual:',
 tensor([[1.],
         [1.],
         [0.]]),
 'predicted:',
 tensor([[0.4851],
         [0.4196],
         [0.4564]], grad_fn=<AddmmBackward>))

## Credits & Links

https://towardsdatascience.com/how-to-train-your-neural-net-tensors-and-autograd-941f2c4cc77c
https://www.analyticsvidhya.com/blog/2018/02/pytorch-tutorial/