# Distance metrics

## Imports & init

In [39]:
import numpy as np
import sklearn.neighbors as sn
dm = sn.DistanceMetric
from dtaidistance import dtw
from dtaidistance import clustering

X = [[0, 1, 2], [3, 4, 5]]
B = [[True, True, False], [False, True, False]]
ts1 = [0, 0, 1, 2, 1, 0, 1, 0, 0]
ts2 = [0, 1, 2, 0, 0, 0, 0, 0, 0]


## Euclidean 

$\large \sqrt(\sum((x - y)^2)) $

In [12]:
dist = dm.get_metric('euclidean')
dist.pairwise(X)

array([[0.        , 5.19615242],
       [5.19615242, 0.        ]])

## Manhattan

$ \large \sum(|x - y|) $

In [13]:
dist = dm.get_metric('manhattan')
dist.pairwise(X)

array([[0., 9.],
       [9., 0.]])

## Chebyshev

$ \large \max(|x - y|) $

In [16]:
dist = dm.get_metric('chebyshev')
dist.pairwise(X)

array([[0., 3.],
       [3., 0.]])

## Minkowski

$ \large \sum(|x - y|^p)^{1/p} $

In [18]:
dist = dm.get_metric('minkowski')
dist.pairwise(X)

array([[0.        , 5.19615242],
       [5.19615242, 0.        ]])

## Hamming

$ \large \frac{-\sum_i^n x_i y_i}{ n } \; \forall \; x_i, y_i = (-1, 1) $   

$ \large \frac{-\sum_i^n |x_i - y_i| }{ n } \; \forall \; x_i, y_i = (0, 1) $  

In [20]:
dist = dm.get_metric('hamming')
dist.pairwise(B)

array([[0.        , 0.33333333],
       [0.33333333, 0.        ]])

## Canberra

$ \large \frac{ \sum |x - y| }{ |x| + |y| } $

In [21]:
dist = dm.get_metric('canberra')
dist.pairwise(B)

array([[0., 1.],
       [1., 0.]])

## DWT

$ \large  $

In [24]:
distance = dtw.distance(ts1, ts2)
print(distance)

1.4142135623730951


In [1]:
from dtaidistance import dtw
series = [
    np.array([0, 0, 1, 2, 1, 0, 1, 0, 0], dtype=np.double),
    np.array([0.0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0]),
    np.array([0.0, 0, 1, 2, 1, 0, 0, 0])]
ds = dtw.distance_matrix_fast(series)

ModuleNotFoundError: No module named 'dtaidistance'

## Distributions

$ \large  $

## Text: cosine distance

$ \large  $

## Clusters

$ \large  $

In [41]:
# Custom Hierarchical clustering
model1 = clustering.Hierarchical(dtw.distance_matrix_fast, {})
cluster_idx = model1.fit(series)
# Augment Hierarchical object to keep track of the full tree
model2 = clustering.HierarchicalTree(model1)
cluster_idx = model2.fit(series)
# SciPy linkage clustering
model3 = clustering.LinkageTree(dtw.distance_matrix_fast, {})
cluster_idx = model3.fit(series)

model.plot("myplot.png")

The compiled dtaidistance C library is not available.
See the documentation for alternative installation options.


Exception: The compiled dtaidistance C library is not available.
See the documentation for alternative installation options.