# Eigenvalues and Eigenvectors

In [6]:
import numpy as np
from numpy.linalg import eig

In [42]:
A = np.array([[1,2,3],[3,2,1],[1,0,-1]])
A

array([[ 1,  2,  3],
       [ 3,  2,  1],
       [ 1,  0, -1]])

To do eigendecomposition of C

In [57]:
lam, vec = eig(A)
print('eigenvalues : ', lam)
print('eigenvectors : \n', vec)

eigenvalues :  [ 4.31662479e+00 -2.31662479e+00  1.93041509e-17]
eigenvectors : 
 [[ 0.58428153  0.73595785  0.40824829]
 [ 0.80407569 -0.38198836 -0.81649658]
 [ 0.10989708 -0.55897311  0.40824829]]


By definition, multiplying an engenvector times the original matrix is the same as multiplying it by the correspondent eigenvalue

In [51]:
print(np.dot(A, vec[:,1]))
print(lam[1] * vec[:,1])

[-1.7049382   0.88492371  1.29493096]
[-1.7049382   0.88492371  1.29493096]


In diagonal matrices, the diagonal values are the eigenvalues

In [58]:
A = np.diag((1, 2, 3))
lam, vec = eig(A)
print('eigenvalues : ', lam)
print('eigenvectors : \n', vec)

eigenvalues :  [1. 2. 3.]
eigenvectors : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Project data into pricipal directions

In [52]:
P = vectors.T.dot(A.T)
P.T

array([[ 1.,  2.,  3.],
       [ 3.,  2.,  1.],
       [ 1.,  0., -1.]])

## Credits & links

https://medium.com/fintechexplained/what-are-eigenvalues-and-eigenvectors-a-must-know-concept-for-machine-learning-80d0fd330e47
http://www.physics.utah.edu/~detar/lessons/python/numpy_eigen/node1.html
https://www.math.ubc.ca/~pwalls/math-python/linear-algebra/eigenvalues-eigenvectors/